# Generated by Django 4.2.29 on 2026-03-18 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('config_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('cover_url', models.URLField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MusicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('external_id', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('playlist', 'Playlist')], max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('artist', models.CharField(blank=True, max_length=256)),
                ('artwork_url', models.URLField(blank=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('playback_ref', models.CharField(blank=True, max_length=512)),
                ('meta_json', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('spoiler', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.collection')),
                ('music_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.musicitem')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('review', 'Review'), ('comment', 'Comment'), ('user', 'User'), ('collection', 'Collection')], max_length=16)),
                ('target_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('review', 'Review'), ('comment', 'Comment'), ('music_item', 'MusicItem')], max_length=16)),
                ('target_id', models.PositiveBigIntegerField()),
                ('value', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, unique=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('favorite_genres', models.TextField(blank=True)),
                ('ui_theme_color', models.CharField(blank=True, max_length=32)),
                ('ui_background', models.CharField(blank=True, max_length=128)),
                ('ui_progress_color', models.CharField(blank=True, max_length=32)),
                ('player_preset', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='musicitem',
            index=models.Index(fields=['title'], name='idx_musicitem_title'),
        ),
        migrations.AddIndex(
            model_name='musicitem',
            index=models.Index(fields=['artist'], name='idx_musicitem_artist'),
        ),
        migrations.AddConstraint(
            model_name='musicitem',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id', 'kind'), name='uniq_music_item_provider_external_kind'),
        ),
        migrations.AddField(
            model_name='listeningevent',
            name='music_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_events', to='core.musicitem'),
        ),
        migrations.AddField(
            model_name='listeningevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='music_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.musicitem'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.review'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.collection'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='music_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_collections', to='core.musicitem'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adunit',
            index=models.Index(fields=['placement', 'is_active'], name='idx_adunit_place_active'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='idx_review_created'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', 'created_at'], name='idx_review_author_created'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('music_item__isnull', False), ('collection__isnull', True)), models.Q(('music_item__isnull', True), ('collection__isnull', False)), _connector='OR'), name='chk_review_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='idx_report_status_created'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['target_type', 'target_id'], name='idx_reaction_target'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user'], name='idx_reaction_user'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='uniq_user_reaction_target'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(check=models.Q(('value__in', [-1, 1])), name='chk_reaction_value_pm1'),
        ),
        migrations.AddIndex(
            model_name='listeningevent',
            index=models.Index(fields=['user', 'started_at'], name='idx_listening_user_started'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'music_item'), name='uniq_user_favorite_music_item'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['review', 'created_at'], name='idx_comment_review_created'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'position'], name='idx_collectionitem_position'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'music_item'), name='uniq_collection_music_item'),
        ),
    ]
