# Generated by Django 4.2 — help_text для приоритета URL над локальным файлом

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_profile_avatar_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicitem",
            name="playback_ref",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Ссылка на воспроизведение (рекомендуется): полный URL https://… "
                    "(YouTube, стриминг, прямой MP3/AAC). Имеет приоритет над файлом на сервере."
                ),
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="musicitem",
            name="audio_file",
            field=models.FileField(
                blank=True,
                help_text=(
                    "Локальная загрузка на сервер — используется в API только если в «Ссылке на воспроизведение» "
                    "нет HTTP(S)-URL."
                ),
                upload_to="music/tracks/",
            ),
        ),
    ]
