# Generated by Django 4.2.29 on 2026-04-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_musicitem_playback_help_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adunit',
            options={'verbose_name': 'Рекламный блок', 'verbose_name_plural': 'Реклама'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборки'},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'verbose_name': 'Элемент подборки', 'verbose_name_plural': 'Элементы подборок'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},
        ),
        migrations.AlterModelOptions(
            name='conversationmember',
            options={'verbose_name': 'Участник диалога', 'verbose_name_plural': 'Участники диалогов'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный трек', 'verbose_name_plural': 'Избранное (треки)'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='listeningevent',
            options={'verbose_name': 'Событие прослушивания', 'verbose_name_plural': 'Дневник прослушиваний'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='musicitem',
            options={'verbose_name': 'Запись каталога', 'verbose_name_plural': 'Каталог музыки'},
        ),
        migrations.AlterModelOptions(
            name='musicitemqualifiedlisten',
            options={'verbose_name': 'Квалифицированное прослушивание', 'verbose_name_plural': 'Квалифицированные прослушивания'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'Реакция', 'verbose_name_plural': 'Реакции'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
        migrations.AlterModelOptions(
            name='reviewfavorite',
            options={'verbose_name': 'Избранная рецензия', 'verbose_name_plural': 'Избранное (рецензии)'},
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='kind',
            field=models.CharField(choices=[('track', 'Трек'), ('album', 'Альбом'), ('playlist', 'Плейлист')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('reaction', 'Реакция'), ('comment', 'Комментарий'), ('follow', 'Подписка'), ('system', 'Системное')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='target_type',
            field=models.CharField(choices=[('review', 'Рецензия'), ('comment', 'Комментарий'), ('music_item', 'Трек каталога')], max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('reviewing', 'На рассмотрении'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('review', 'Рецензия'), ('comment', 'Комментарий'), ('user', 'Пользователь'), ('collection', 'Подборка')], max_length=16),
        ),
    ]
