# Generated by Django 4.2.29 on 2026-04-16 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_musicitem_artist_user'),
        ('core', '0011_remove_musicitem_playback_ref'),
    ]

    operations = [
    ]
