# Generated by Django 4.2.30 on 2026-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20260416_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicitem',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Локальная загрузка трека на сервер. Используется для воспроизведения в приложении.', upload_to='music/tracks/'),
        ),
    ]
