# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_musicitem_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="adunit",
            name="banner_image",
            field=models.FileField(blank=True, default="", upload_to="ads/banners/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adunit",
            name="config_json",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
