# Generated by Django 4.2.29 on 2026-05-14 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_adunit_banner_image_config_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.collection'),
        ),
        migrations.AlterField(
            model_name='review',
            name='music_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.musicitem'),
        ),
    ]
