# Generated by Django 4.2.29 on 2026-05-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_review_targets_delete_with_parent'),
        ('core', '0015_alter_review_fk_cascade'),
    ]

    operations = [
    ]
